---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/data:/data #optional
    ports:
      - 8989:8989
    restart: unless-stopped