---
version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /volume1/docker/bazarr/config:/config
      - /volume1/data/media/movies:/movies #optional
      - /volume1/data/media/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - /volume1/docker/deluge/config:/config
      - /volume1/data/torrents:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /volume1/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
      - AUTO_UPDATE=true #optional
    volumes:
      - /volume1/docker/jackett/config:/config
      - /volume1/data/torrents/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - /volume1/docker/plex/config:/config
      - /volume1/data/media/tv:/tv
      - /volume1/data/media/movies:/movies
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /volume1/docker/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - PMM_CONFIG=/config/config.yml
      - PMM_TIME=03:00 #optional
      - PMM_RUN=False #optional
      - UMASK_SET=022
    volumes:
      - /volume1/docker/plex/config:/config
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/data:/data #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/data:/data #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /volume1/docker/homeassistant/config:/config
    restart: unless-stopped
  actualserver:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    # environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    volumes:
      - /volume1/docker/actualserver:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
