---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID} 
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - /volume1/plex/config:/config
      - /media/tv:/tv
      - /media/movies:/movies
    restart: unless-stopped